Adds Dunst And Removes 'exit' functions in i3lock script

diff --git a/modules/x/i3/scripts/lock b/modules/x/i3/scripts/lock
--- a/modules/x/i3/scripts/lock
+++ b/modules/x/i3/scripts/lock
@@ -17,21 +17,41 @@ font="sans-serif"
 locktext='Type password to unlock...'
 temp_pic='/tmp/i3lock.png'
 
-/usr/bin/scrot -o -q 100 $temp_pic || exit 1
+log_error() {
+    echo "[i3lock] Error: $*" >&2
+}
 
-/usr/bin/convert $temp_pic -paint 3 -swirl 270 $temp_pic || exit 1
+main() {
+    if ! /usr/bin/scrot -o -q 100 $temp_pic; then
+        log_error "scrot failed"
+        return 1
+    fi
 
-/usr/bin/i3lock \
-    -t -e -i $temp_pic \
-    --time-pos='x+110:h-70' \
-    --date-pos='x+43:h-45' \
-    --clock --date-align 1 --date-str "$locktext" \
-    --inside-color=$insidecolor --ring-color=$ringcolor --line-uses-inside \
-    --keyhl-color=$keyhlcolor --bshl-color=$bshlcolor --separator-color=$separatorcolor \
-    --insidever-color=$insidevercolor --insidewrong-color=$insidewrongcolor \
-    --ringver-color=$ringvercolor --ringwrong-color=$ringwrongcolor --ind-pos='x+280:h-70' \
-    --radius=20 --ring-width=4 --verif-text='' --wrong-text='' \
-    --verif-color="$verifcolor" --time-color="$timecolor" --date-color="$datecolor" \
-    --time-font="$font" --date-font="$font" --layout-font="$font" --verif-font="$font" --wrong-font="$font" \
-    --noinput-text='' --force-clock --pass-media-keys \
-    || exit 1
+    if ! /usr/bin/convert $temp_pic -paint 3 -swirl 270 $temp_pic; then
+        log_error "convert failed"
+        return 1
+    fi
+
+    if ! /usr/bin/i3lock \
+        -t -e -i $temp_pic \
+        --clock --time-pos='x+110:h-70' \
+        --date-align 1 --date-str "$locktext" --date-pos='x+43:h-45' \
+        --inside-color="$insidecolor" --ring-color="$ringcolor" --line-uses-inside \
+        --keyhl-color="$keyhlcolor" --bshl-color="$bshlcolor" --separator-color="$separatorcolor" \
+        --insidever-color="$insidevercolor" --insidewrong-color="$insidewrongcolor" \
+        --ringver-color="$ringvercolor" --ringwrong-color="$ringwrongcolor" --ind-pos='x+280:h-70' \
+        --radius=20 --ring-width=4 \
+        --verif-text='' --wrong-text='' --noinput-text='' \
+        --verif-color="$verifcolor" --time-color="$timecolor" --date-color="$datecolor" \
+        --time-font="$font" --date-font="$font" --layout-font="$font" \
+        --verif-font="$font" --wrong-font="$font" \
+        --force-clock --pass-media-keys
+    then
+        log_error "i3lock failed"
+        return 1
+    fi
+
+    return 0
+}
+
+main "$@"
